name: Cypress tests
on:
    pull_request:
        branches:
            - '*'
jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@master
            - name: Install root dependencies
              uses: bahmutov/npm-install@v1

            - name: Start server in the background
              run: npm start &

            # Cypress has its own package.json in folder "e2e"
            - name: Install Cypress and run tests
              uses: cypress-io/github-action@v5
